//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp1.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.7.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Name {
            get {
                return ((string)(this["Name"]));
            }
            set {
                this["Name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Password {
            get {
                return ((string)(this["Password"]));
            }
            set {
                this["Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9:30")]
        public string InTime {
            get {
                return ((string)(this["InTime"]));
            }
            set {
                this["InTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9:40")]
        public string LaterTime {
            get {
                return ((string)(this["LaterTime"]));
            }
            set {
                this["LaterTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10:00")]
        public string NoneTime {
            get {
                return ((string)(this["NoneTime"]));
            }
            set {
                this["NoneTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18:00")]
        public string OutTime {
            get {
                return ((string)(this["OutTime"]));
            }
            set {
                this["OutTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int EmptyType {
            get {
                return ((int)(this["EmptyType"]));
            }
            set {
                this["EmptyType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int LaterType {
            get {
                return ((int)(this["LaterType"]));
            }
            set {
                this["LaterType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int NoneType {
            get {
                return ((int)(this["NoneType"]));
            }
            set {
                this["NoneType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0:00,0:00,2,True,Firebrick,上班未打卡|
0:00,9:30,0,True,ForestGreen,|
9:30,9:40,1,True,Sienna,|
9:40,10:00,1,True,Firebrick,|
10:00,12:00,2,True,Firebrick,|
12:00,18:00,0,True,Firebrick,|
18:00,22:00,0,False,Green,|
22:00,23:59,0,False,Green,|
0:00,0:00,2,False,DarkGoldenrod,下班未打卡")]
        public string TimeTypes {
            get {
                return ((string)(this["TimeTypes"]));
            }
            set {
                this["TimeTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"0:00,0:00,2,True,Firebrick,上班未打卡|
0:00,9:30,0,True,ForestGreen,|
9:30,9:40,1,True,Sienna,|
9:40,10:00,1,True,Firebrick,|
10:00,12:00,2,True,Firebrick,|
12:00,18:00,0,True,Firebrick,|
18:00,22:00,0,False,Green,|
22:00,23:59,0,False,Green,|
0:00,0:00,2,False,DarkGoldenrod,下班未打卡")]
        public string OrgTimeTypes {
            get {
                return ((string)(this["OrgTimeTypes"]));
            }
            set {
                this["OrgTimeTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22:00,1.00:00,10:00,LightCoral|1.00:00,1.9:00,13:30,Red")]
        public string TimeReourde {
            get {
                return ((string)(this["TimeReourde"]));
            }
            set {
                this["TimeReourde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("22:00,1.00:00,10:00,LightCoral|1.00:00,1.9:00,13:30,Red")]
        public string OrgTimeReourde {
            get {
                return ((string)(this["OrgTimeReourde"]));
            }
            set {
                this["OrgTimeReourde"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool enableOutTime {
            get {
                return ((bool)(this["enableOutTime"]));
            }
            set {
                this["enableOutTime"] = value;
            }
        }
    }
}
